### ISSUE TITLE
[BUG] Missing brackground color on search input field (.mat-select-search-input)

### ISSUE THREAD

**Issue by melroy89** [bithost-gmbh/ngx-mat-select-search#542]
**Describe the bug**

~~The search input field seems to have the wrong z-index on the latest Angular / Angular material design (m3).~~

The background-color is not set on the latest Angular material design (m3). Because `--mat-select-panel-background-color` is no longer used. Use `--mat-sys-surface-container` instead.

Causing the scrollable mat-option text to be seen behind the search field? Quite an annoying UI bug.

**To Reproduce**

1. Use the latest Angular version (19.2.7)
2. Use the latest [Angular Material](https://material.angular.io/guide/getting-started) version (19.2.10)
3. Use the latest CDK (19.2.10)
4. Use Material 3 design (m3), something like this will do:

    ```scss
    @use '@angular/material' as mat;

    html {
      @include mat.theme(
        (
          color: (
            primary: mat.$azure-palette,
            tertiary: mat.$blue-palette
          ),
          typography: Roboto,
          density: 0
        )
      );
    }
    ```
5. Use `ngx-mat-select-search`

**Screenshots**

![Image](https://github.com/user-attachments/assets/260d2856-8443-4529-8bae-34fbfe856a88)

![Image](https://github.com/user-attachments/assets/9ead5aea-4d81-4dd5-9494-f12d853937d0)

**Additional information**

Use `--mat-sys-surface-container`, see here: https://material.angular.io/components/select/styling

But that might break m2.

**Desktop (please complete the following information):**
 - OS: Linux Mint 
 - Browser: Floorp (Firefox)
 - Version: 11.25.0
