### ISSUE TITLE
Rendering issue when selector is at bottom of viewport

### ISSUE THREAD

**Issue by hadsy** [bithost-gmbh/ngx-mat-select-search#63]
Great component but we are just having strange rendering issue when the selector is at the bottom of the viewport. Is there any CSS we can use to override this?
I've tried using disableOptionCentering on the mat-select but this has no effect for me.
Many thanks

![image](https://user-images.githubusercontent.com/1922001/46468763-4d0f4380-c7c9-11e8-9505-e35fd774c868.png)

**Comment by macjohnny** [comment]
@hadsy this seems to be related to 
```css
.mat-select-search-panel {
  ...
  max-height: 350px;
}
```
see https://github.com/bithost-gmbh/ngx-mat-select-search/blob/1.4.0/src/app/mat-select-search/mat-select-search.component.scss#L39

Setting it to the original value (https://github.com/angular/material2/blob/master/src/lib/select/select.scss#L9) seems to resolve the issue:
```css
.mat-select-search-panel {
  ...
  max-height: 256px;
}
```
I will release  a patch version that removes this css property, using the original value.
